<<<<<<< HEAD
development:
  adapter: postgresql
  encoding: unicode
  database: daybook_dev
  pool: 5
  username: postgres
  password:
 
  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  #host: localhost
  #port: 5432
 
  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public
 
  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # The server defaults to notice.
  #min_messages: warning
 
=======
# SQLite version 3.x
#   gem install sqlite3
#   lol
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

local: &local
  adapter: postgresql
  username: azaza
  password: pwd
  host: localhost




development:
  <<: *local
  database: organizer_dev


>>>>>>> 1f1db5b1b82a0d0e1ce7051a99a4b8e350be6cd8
# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
<<<<<<< HEAD
  adapter: postgresql
  encoding: unicode
  database: daybook_test
  pool: 5
  username: postgres
  password:
 
production:
  adapter: postgresql
  encoding: unicode
  database: daybook_prod
  pool: 5
  username: postgres
  password:
=======
  <<: *local
  database: organizer_test


production:
  <<: *local
  database: organizer_production
>>>>>>> 1f1db5b1b82a0d0e1ce7051a99a4b8e350be6cd8
